spring:
  application:
    name: be
  datasource:
    url: jdbc:postgresql://localhost:5432/coursy-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 9002
auth:
  service:
    url: http://localhost:9000